openapi: 3.0.0
info:
  title: Resources API
  description: Resource Demo API by Sunny Adeshara
  contact:
    name: Sunny Adeshara
    email: sunnyadeshara@gmail.com
    url: apis.sunnyadeshara.in
  version: 1.0.0
servers:
  - url: https://apiserver1.sunnyadeshara.in/v1
  - url: https://apiserver2.sunnyadeshara.in/v1
paths:
  /appointment:
    description: An appointment
    get:
      description: Operations to manage an appointment
      parameters:
        - in: query
          name: title
          required: true
          schema:
            type: string
            example: Appointment for doctor
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appointments'
    post:
      description: Add a new appointment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/appointment'
      responses:
        201:
          description: Successfully added!
    put:
      description: Add a new appointment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/appointment'
      responses:
        201:
          description: Successfully updated!
  /appointment/{id}:
    description: Get appointment based on id
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Appointment found successfully!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appointment'
            application/xml:
              schema:
                $ref: '#/components/schemas/appointment'
components:
  schemas:
    appointment:
      type: object
      properties:
        AppointmentID:
          type: integer
          example: 3
        Title:
          type: string
          example: Doctor
        Resource:
          type: string
          example: For doctor's appointment
    appointments:
      type: array
      items:
        properties:
          AppointmentID:
            type: integer
            example: 3
          Title:
            type: string
            example: Doctor
          Resource:
            type: integer
            example: 1